### ISSUE TITLE
proposal: `createProvider(providerId: string)`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_kv_oauth#11]
The 2nd parameter would be `additionalOauth2ClientConfig?: OAuth2ClientConfig`, allowing one to override the default OAuth config. This would also be used under the hood in other functions that use `oauth2Client` to provide additional customizability. E.g. `signIn(provider: Provider)` -> `signIn(provider: ProviderId | Provider)`.

I think having a single function that constructs `Provider` objects over having multiple means better DX. Also, such a feature would be very cheap to implement if using a basic switch statement.

**Comment by lino-levan** [comment]
What are the advantages of this over `createXProvider` (outside of a stable API)? I feel like one or the other would make sense. My optimal API interface would be `createProvider(providerId)` with something like `listProviders()` or just an exported list of allowed providers.

**Comment by iuioiua** [comment]
Implemented in #22.
