### ISSUE TITLE
suggestion: add Ultra framework demo

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_kv_oauth#120]
The demo should be minimal and roughly look like the demo in this repo. Once created, a link to the demo repo can be added to the "In the Wild" README section. See the [Oak + Deno KV OAuth Demo](https://dash.deno.com/playground/oak-deno-kv-oauth-demo) for reference.

**Comment by mbhrznr** [comment]
always wanted to give ultra a shot, would take a look at this one.

**Comment by iuioiua** [comment]
Great! To be clear, the example itself would be in another repo. The link to that repo would be in the "In the Wild" README section.

**Comment by mbhrznr** [comment]
just a quick heads-up:
i've created a demo, yet i'm failing to deploy it to deno deploy.

i've also opened an issue as it looks like some of the dependencies couldn't be resolved properly:
https://github.com/exhibitionist-digital/ultra/issues/265

**Comment by deckchairlabs** [comment]
> just a quick heads-up: i've created a demo, yet i'm failing to deploy it to deno deploy.
> 
> i've also opened an issue as it looks like some of the dependencies couldn't be resolved properly: [exhibitionist-digital/ultra#265](https://github.com/exhibitionist-digital/ultra/issues/265)

Happy to help out with any issues you come across trying to implement this demo! Interested to see how it goes

**Comment by mbhrznr** [comment]
> Happy to help out with any issues you come across trying to implement this demo! Interested to see how it goes

once again, thanks for the quick help!
had some real live stuff going on, but code wise it was smooth sailing!
