### ISSUE TITLE
suggestion: better look of demo

### ISSUE THREAD

**Issue by huai-jie** [denoland/deno_kv_oauth#127]
![image](https://github.com/denoland/deno_kv_oauth/assets/58794979/4fb1aed8-61fd-40fa-9b49-dc5f71e45f83)

**Comment by iuioiua** [comment]
The demo aims to show the bare minimum required functionality and implementation for authentication. It's OK for the demo to be ugly as long as it's usable and understandable. While styling makes it more appealing, it adds to the amount the dev has to read through to understand the implementation.

**Comment by huai-jie** [comment]
I see. Okay, I would close this issue then.
