### ISSUE TITLE
Oak Demo (change to undefine)

### ISSUE THREAD

**Issue by adoublef** [denoland/deno_kv_oauth#139]
Last week I was attempting to recreate the demo but with Auth0, all was good but I had to change this line to `undefined` as it seems `getSessionId` now returns `undefined` so this boolean checks fails.

```typescript
const isSignedIn = sessionId !== null; // this may need to be changed to undefined
```

**Comment by iuioiua** [comment]
Good catch! I've updated that example and the Fresh example. Thank you.
