### ISSUE TITLE
Auth0 example

### ISSUE THREAD

**Issue by adoublef** [denoland/deno_kv_oauth#140]
I've made the issue [here](https://github.com/cmd-johnson/deno-oauth2-client/issues/33) but as this package depends on it and the docs show Auth0 being supported wanted to bring it to your attention too.

Auth0 will return an invalid JWT unless the audience is added to the Uri. Looking at the code it doesn't seem that there's currently a way to allow this

**Comment by iuioiua** [comment]
> Auth0 will return an invalid JWT unless the audience is added to the Uri.

Could you please clarify? Added to which URI? In which function is the invalid JWT being returned? In which part of the code are you expecting to see a JWT? Also, in your use case, is the audience required? A brief look at [the documentation](https://community.auth0.com/t/what-is-the-audience/71414) says that it's optional.

**Comment by adoublef** [comment]
The audience is required for so that the token that is returned isn't opaque but an access token (as this YouTube vid shares: [Why is my Access Token not a JWT? (Opaque Token) -- Auth0 Community Response Series - YouTube](https://www.youtube.com/watch?v=HjbPRGlLiwM)). Due to this, you aren't able to use the token for subsequential requests using APIs configured in Auth0. Looks like an issue with the way [getAuthorizationUri](https://github.com/cmd-johnson/deno-oauth2-client/blob/master/src/authorization_code_grant.ts#L96) is created doesn't give an option to append your own params. 

Ran into similar issue with a Go package that I use but they offer an additional method to set optional url params. 

I don't think it's something that can be fixed without forking or waiting for the original author to fix but this will make using Auth0 incomplete.

**Comment by cmd-johnson** [comment]
Copying what I just wrote at [cmd-johnson/deno-oauth2-client#33](https://github.com/cmd-johnson/deno-oauth2-client/issues/33#issuecomment-1640570550), the URI returned by `getAuthorizationUri` is an instance of the URL class, so you can just add additional parameters as needed by calling `uri.searchParams.set("paramName", "value");`

**Comment by iuioiua** [comment]
@adoublef, can you confirm that this module works with Auth0?

**Comment by adoublef** [comment]
Oh yes all that is needed is audience and you get a token that can be used with the APIs. I tested with generating the token and then using an existing go API with the required scope. 

I've not yet made an Auth0 API using Deno but I'm looking at the node example on their site to replicate so I've a full Deno example.

Hopefully that makes sense

**Comment by iuioiua** [comment]
Great to hear! Thanks for helping! 💪🏾

**Comment by brianknight10** [comment]
@iuioiua Will you be cutting a new release with this change anytime soon? Thank you!

**Comment by iuioiua** [comment]
Just done - https://github.com/denoland/deno_kv_oauth/releases/tag/v0.2.8

**Comment by brianknight10** [comment]
Thanks mate!
