### ISSUE TITLE
How to get user details on callback success

### ISSUE THREAD

**Issue by vinaybedre** [denoland/deno_kv_oauth#154]
I searched all the existing issues and docs, I was only able to figure out, how to get the sessionId or accessToken. 

How can one get user details from accessToken? Should we connect to 3rd party APIs separately?

**Comment by mitchwadair** [comment]
Typically you'd either get user information from an ID Token or from a separate user info endpoint using the access token. For the former, this library currently does not support ID Tokens, as they are part of the OIDC spec, and not the OAuth2 spec. This could change in the future, of course, but your best bet for now would be to make a request to a user info endpoint if it is available on the service you are using

**Comment by iuioiua** [comment]
> Typically you'd either get user information from an ID Token or from a separate user info endpoint using the access token. For the former, this library currently does not support ID Tokens as they are part of the OIDC spec, and not the OAuth2 spec. This could change in the future, of course, but your best bet for now would be to make a request to a user info endpoint if it is available on the service you are using

Correct! For now, you'll have to use your access token to make a REST API call to your provider. This is how Deno SaaSKit does it: https://github.com/denoland/saaskit/blob/617fd6f975b924cc5d9c80b0f4e41a2d424aa757/routes/callback.ts#L18-L32

Once [x/oauth2_client](https://deno.land/x/oauth2_client) supports OIDC ([related](https://github.com/cmd-johnson/deno-oauth2-client/issues/29)), we'll aim to have this module do the same to make this all easier.

Either way, I should add a small section to the README that answers your question.
