### ISSUE TITLE
Callback redirection to the original page

### ISSUE THREAD

**Issue by jollytoad** [denoland/deno_kv_oauth#172]
How can you pass the callback redirection URL through the entire flow?

To clarify, I mean the URL that the callback handler redirects to - which is currently passed as the third arg to `handleCallback`.

I'd like the 'Referer' (or other arbitrary URL) to be passed from signin, all the way through the flow to the callback handler, so that the user ends up back on the same page after.

I've tried adding it to the callback URL, but some providers (eg. Google), don't allow this.

**Comment by iuioiua** [comment]
In Deno SaaSKit, we do this by setting a "redirect cookie". See https://github.com/denoland/saaskit/blob/e27502ed610489e0e94bb7bee9eafee7a610a04e/routes/signin.ts#L14

**Comment by iuioiua** [comment]
Frankly, I've asked myself the same question and haven't yet come up with another solution.

**Comment by jollytoad** [comment]
Thank you very much, I'd not considered that, tbh, I generally try to avoid cookies as far as I can, so it never occurs to me to leverage them for something like this. Anyway, this approach works a treat for me.

I'm not sure what other approach would be suitable.

Alternatives off the top of my head:
* Encoded in the 'state' param?
* Stored in KV?

**Comment by iuioiua** [comment]
Storing the URL in KV seems like an interesting idea 🤔

**Comment by jollytoad** [comment]
If it works, maybe the default behaviour should be for `signIn` to take the `Referer` header, unless explicit overridden in a signIn option? and the callback handler to default to this saved URL, again unless explicitly overridden. 
I think this would provide a reasonable default behaviour of least surprise. WDYT?

**Comment by iuioiua** [comment]
That's the right direction! The success URL could be defined by:
1. A `success_url` URL parameter, if provided.
2. If the above is not provided, the `Referer` header value (must be of the same origin).
3. If the above is not provided, the homepage, `/`, by default.

WDYT?

**Comment by jollytoad** [comment]
This is such an amazing turn around, thank you very much for your help on this and the new out of the box support for the redirection.

**Comment by iuioiua** [comment]
Thanks for the suggestion! The feature is now included in the latest [v0.5.0 release](https://github.com/denoland/deno_kv_oauth/releases/tag/v0.5.0)!

**Comment by jollytoad** [comment]
Already upgraded, has simplified my code quite a bit... https://github.com/jollytoad/home/commit/61558424b03eb3b67f6451778fd956ebdf591593
