### ISSUE TITLE
Suggestion: support relative redirectUri

### ISSUE THREAD

**Issue by jollytoad** [denoland/deno_kv_oauth#195]
At present a redirectUri is passed wholesale through the flow, and so must be configured as an absolute URL.
This often means you have to know your origin in advance or you have to configure your redirectUri and client at request time.

Example:
```ts
const redirectUri = new URL("/callback", req.url).href;
const client = createSomeOAuth2Client({ redirectUri });
return signIn(req, client);
```

As you are already passing the Request to the signIn/callbackHandler, these could resolve the URL instead...

```ts
const client = createSomeOAuth2Client({ redirectUri: "/callback" });
return signIn(req, client);
```

**Comment by iuioiua** [comment]
Sorry for the delay. I'm mostly +1 for this, as long as the logic involved is minimal. Perhaps, we can create a small wrapper with a signature like:
```ts
toAbsoluteRedirectUri(oauthConfig: OAuth2ClientConfig): OAuth2ClientConfig;
```

**Comment by iuioiua** [comment]
I've thought about this further after implementing #257. On second thought, the redirect URI should be one of those things that should be manually controlled by the web dev, even if inconvenient. I also think that, while simple, this adds to the list of security considerations. To be clear, I still think this is cool in terms of ease-of-use for the web dev, but it doesn't justify the possible security tradeoff. Thank you, either way 🙂
