### ISSUE TITLE
Suggestion: Common configuration function with validation

### ISSUE THREAD

**Issue by jollytoad** [denoland/deno_kv_oauth#196]
The providers are very repetitive atm, they don't validate the config, and attempt to get the env vars for id/secret even if those values are passed in the given additional config props, meaning that a consume of the lib must allow envs.

```ts
  return new OAuth2Client({
    clientId: Deno.env.get("GOOGLE_CLIENT_ID")!,
    clientSecret: Deno.env.get("GOOGLE_CLIENT_SECRET")!,
    authorizationEndpointUri: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUri: "https://oauth2.googleapis.com/token",
    ...additionalOAuth2ClientConfig,
  });
```

a simply function could standardize this, providing validation that all values are set as required and provide a place to improve/fix issues should they crop up (eg. fallback on env vars rather than requiring them).

a simple example of usage of such a fn:

```ts
const config = createOAuthConfig({
  name: "Google",
  authorizationEndpointUri: "https://accounts.google.com/o/oauth2/v2/auth",
  tokenUri: "https://oauth2.googleapis.com/token",
  ...additionalOAuth2ClientConfig,
});
```

**Comment by iuioiua** [comment]
This might be best as an internal function. Are you able to open a separate PR so we can explore this further? 🙂
