### ISSUE TITLE
Suggestion: Providers provide a reasonable default scope

### ISSUE THREAD

**Issue by jollytoad** [denoland/deno_kv_oauth#197]
If you using kv_oauth for authentication, it useful to have a scope that provides access to a reasonable set of user details, and maybe OIDC (#194) if supported by the provider.

A reasonable initial developer experience would be to not have to explicitly find the scopes for a provider for this, and so it seems reasonable that a provider also provides a default scope, which can be completely overridden when supply by the developer.

**Comment by iuioiua** [comment]
While this module aims to be high-level, defining a default scope seems to be overreaching. The scope is one of the parameters that the developer should know and explicitly define when using this module. I don't see why this should be the responsibility of this module.
