### ISSUE TITLE
Suggestion: Granular imports from kv_oauth and clarity of internal modules

### ISSUE THREAD

**Issue by jollytoad** [denoland/deno_kv_oauth#198]
Importing the whole `mod.ts` or individual modules as required should be the choice of the library consumer.

For example, it's reasonable to just import "/src/sign_in.ts" if you only want the `signIn` function.

It's not clear which modules are meant to just be internal, I'd recommend following the same convention as the std lib here and clearly mark modules or folders of modules with `_` prefix.

I **don't** think just saying only `mod.ts` is public and everything else is internal is a reasonable approach either, as this really goes against the benefits of the granular URL imports of Deno, and drags us back into the dependency hell days of npm. (I've ellaborated on this in an article here, so I won't repeat everything: https://jollytoad.deno.dev/blog/dependency_hell)

To be clear though, I'm not suggesting dropping `mod.ts`, just acknowledge the choice of the developer to pick and choose modules directly, and help guide them with the `_internal/here_be_dragons.ts` style convention.

I would also advocate for either ditching `deps.ts` or at least making the imports within `deps.ts` into more direct module imports rather than import the whole `mod.ts` from another lib.

**Comment by iuioiua** [comment]
The `/src` folder is internal. The `mod.ts` file is the only file that needs to be imported for any use of this module. I thought this was clear, given the documentation never references imports from the `/src` folder in any of its examples. However, we can document that somewhere if it needs to be clarified.

I usually agree that there should be one file per function. In fact, I was one of the leading proponents of the single-export files that the Standard Library uses today. However, one should first ask why before imposing a requirement. Single-export files make sense in a library when there's a high likelihood of functions being used by themselves. With this module, you'll likely use most functions to sign in, sign out, handle the callback, create a preset OAuth client for a given provider, etc. I can't think of any case that'd, say, require `signIn()` only. For this reason, when creating this module, I opted for a slightly better file structure, IMO, by having a single entry point, `mod.ts` and implementation code within `/src`.

**Comment by iuioiua** [comment]
Actually, I think this is a good idea now. PTAL at #218.
