### ISSUE TITLE
bug: Token Refresh Logic is Reversed

### ISSUE THREAD

**Issue by mitchwadair** [denoland/deno_kv_oauth#199]
Sorry if I'm being dumb here, but I was reading through the code to get a better idea of how tokens are stored/used etc and noticed this. If I am reading this right, the function is returning the access token if there is no refresh token or if `tokens.expiresIn` is both truthy (meaning both defined and non-zero) and less than 5.

https://github.com/denoland/deno_kv_oauth/blob/b4007c04c55a840ac8451037e947c63162c0ae60/src/get_session_access_token.ts#L30-L36

I think there is one main issue with this. If `expiresIn` is a non-zero value that is less than 5, we probably _do_ want to refresh the token right? There are two cases:
1. `expiresIn` is negative, meaning it is already expired and we should refresh
2. `expiresIn` indicates that the token will expire soon (the 5 second buffer mentioned in the comment) and we should refresh

With the current logic, isn't the function basically only refreshing the token if it is not going to expire soon or if `expiresIn` is _exactly_ `0`? Should that `<` actually be a `>`? Or am I crazy

This would definitely be problematic because there would likely be a large number of requests being made to oauth providers and a bunch KV writes that are unnecessary

**Comment by mitchwadair** [comment]
I believe I have also figured out why tests are passing with this logic:
In the `genTokens` helper, `refreshToken` is not defined
https://github.com/denoland/deno_kv_oauth/blob/b4007c04c55a840ac8451037e947c63162c0ae60/src/test_utils.ts#L20-L25
Because of this, the test for long-expiry passes because this function automatically returns the access token when `refreshToken` is undefined
https://github.com/denoland/deno_kv_oauth/blob/b4007c04c55a840ac8451037e947c63162c0ae60/src/get_session_access_token_test.ts#L22

I am happy to PR a fix to this problem if my assessment here is correct, lmk

**Comment by mitchwadair** [comment]
Actually even more issues here than I thought.

The `expiresIn` property is documented as the time in seconds, but it is multiplied by `SECOND`, making the condition here off by a factor of 1000 in addition to what I already mentioned here

**Comment by iuioiua** [comment]
> Sorry if I'm being dumb here, but I was reading through the code to get a better idea of how tokens are stored/used etc and noticed this. If I am reading this right, the function is returning the access token if there is no refresh token or if `tokens.expiresIn` is both truthy (meaning both defined and non-zero) and less than 5.
> 
> 
> 
> https://github.com/denoland/deno_kv_oauth/blob/b4007c04c55a840ac8451037e947c63162c0ae60/src/get_session_access_token.ts#L30-L36
> 
> 
> 
> I think there is one main issue with this. If `expiresIn` is a non-zero value that is less than 5, we probably _do_ want to refresh the token right? There are two cases:
> 
> 1. `expiresIn` is negative, meaning it is already expired and we should refresh
> 
> 2. `expiresIn` indicates that the token will expire soon (the 5 second buffer mentioned in the comment) and we should refresh
> 
> 
> 
> With the current logic, isn't the function basically only refreshing the token if it is not going to expire soon or if `expiresIn` is _exactly_ `0`? Should that `<` actually be a `>`? Or am I crazy
> 
> 
> 
> This would definitely be problematic because there would likely be a large number of requests being made to oauth providers and a bunch KV writes that are unnecessary

You're not crazy. That's a bug. Yes, please do feel free to open a PR 🙂

**Comment by iuioiua** [comment]
> Actually even more issues here than I thought.
> 
> 
> 
> The `expiresIn` property is documented as the time in seconds, but it is multiplied by `SECOND`, making the condition here off by a factor of 1000 in addition to what I already mentioned here.
> 
> 
> 
> Also, when calculating `expiresIn` it is reversed as well
> 
> https://github.com/denoland/deno_kv_oauth/blob/b4007c04c55a840ac8451037e947c63162c0ae60/src/core.ts#L146-L147
> 
> Here, the `expiresIn` should be calculated by the current time subtracted from the `expiresAt` time

Ah, yes, I think you're right. Thanks for picking up on these. I'll submit fixes as soon as I can. Great work. Thank you.

**Comment by iuioiua** [comment]
I'll do a full review of the codebase to ensure there aren't any more of these silly mistakes. Thanks for pointing them out.

**Comment by mitchwadair** [comment]
> Ah, yes, I think you're right. Thanks for picking up on these. I'll submit fixes as soon as I can. Great work. Thank you.

I can get a PR up soon with fixes for the issues mentioned in this issue soon so you can focus on other things 👍

**Comment by iuioiua** [comment]
Great! Thank you. I believe these issues deserve 2 PRs. Please be sure to provide an explanation of the issues too 🙂

**Comment by mitchwadair** [comment]
PRs are up!
