### ISSUE TITLE
proposal: add cookie options to `handleCallback()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_kv_oauth#20]
[`handleCallback()` sets a site session cookie in the response.](https://github.com/denoland/deno_kv_oauth/blob/3a7339372754b2b68041ac78ad0870740b67fad8/mod.ts#L104-L109) This cookie should be configurable but with reasonable defaults.

**Comment by lino-levan** [comment]
Is this referring to JWT? Confused as to what this means.

**Comment by lino-levan** [comment]
Maybe this is the wrong way of building software, but I wonder if we should wait for someone to complain about this before implementing it. Adding unnecessary options is pretty hurtful to the long-term maintainability of modules in my experience.

**Comment by iuioiua** [comment]
Yeah, I was thinking along the same lines.

**Comment by iuioiua** [comment]
Closing as having reasonable default cookies should mitigate any need to customise cookies.
