### ISSUE TITLE
Failed to delete OAuth session

### ISSUE THREAD

**Issue by bdodroid** [denoland/deno_kv_oauth#278]
Everything seems fine until it tries to delete the KV entry

```
  const res = await kv.atomic()
    .check(oauthSessionRes)
    .delete(key)
    .commit();
```

at which point it throws

```
Failed to delete OAuth session
```

I am running with --unstable and --allow-all.

No idea why this is failing. My keys and domain are set for Auth0 and Auth0 is configured to point everything to my localhost.

**Comment by iuioiua** [comment]
Can you please share the full snippet?

**Comment by iuioiua** [comment]
I created an Auth0 account and successfully signed in without issue. I wasn't able to reproduce the issue.

I can't say, with confidence, why the commit within `getAndDeleteOAuthSession()` is failing. Unfortunately, KV doesn't yet provide much insight into why commits fail, but [there's work in progress](https://github.com/denoland/deno/pull/20689) that should fix that.

Can you please share your `deno --version` output? Also, has this only happened once or does this happen repeatedly?

<img width="616" alt="image" src="https://github.com/denoland/deno_kv_oauth/assets/29347852/a7931e06-f904-4545-83d3-4779afdcd2b8">

**Comment by iuioiua** [comment]
But yes, please let me know how you go on Deploy and the other machine.

**Comment by bdodroid** [comment]
Looks like it is an issue with my setup on my windows environment.

Just tried it on my debian laptop with the same exact code (and deno version) and it ran fine, and my deploy to deno.deploy is working just fine as well.

Not sure what my issue is on windows.

Appreciate your help @iuioiua !

**Comment by iuioiua** [comment]
Oh, that's good to hear. Thanks for bringing this up! Glad I could be of assistance.
