### ISSUE TITLE
todo: update Oak example

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_kv_oauth#308]
We should update Oak to the latest version.

See https://discord.com/channels/684898665143206084/688040863313428503/1210625832918323240

**Comment by e-osuna-g** [comment]
i have made the example almost completely work except for this function getSessionAccessToken, i dont know exatly how the last one worked,  but it would be of great help if we can make it work to access simple user information to be shown, i can add my changes that made it work in my case if needed.

**Comment by e-osuna-g** [comment]
follow up: in the original example a request with body is used, but all requests are GET wich do not have a body. isn't just better to just set null value to body? (this is what i'm doing to make it work)

**Comment by iuioiua** [comment]
I've now updated the Oak example to use JSR and the latest packages.

@e-osuna-g, `getSessionAccessToken()` was removed in #224 in favor of the `tokens` property returned from the [`handleCallback()`](https://jsr.io/@deno/kv-oauth/doc/~/Helpers.handleCallback) method. By using `tokens.accessToken` in `handleCallback()`, you can make calls to whatever authenticated endpoint you need to.

Closing this issue now. Please feel free to open an issue or message me in Discord if you need any help with anything else.
