### ISSUE TITLE
AWS Cognito provider?

### ISSUE THREAD

**Issue by gdtroszak** [denoland/deno_kv_oauth#310]
Is there any interest in adding an AWS Cognito provider? I recently used kv-oauth to interact with a Cognito user pool and would be happy to clean it up and contribute. I could also include some CDK for a basic Cognito setup if that would be helpful.

**Comment by iuioiua** [comment]
> Is there any interest in adding an AWS Cognito provider? I recently used kv-oauth to interact with a Cognito user pool and would be happy to clean it up and contribute.

That'd be great! A PR would be welcome.

> I could also include some CDK for a basic Cognito setup if that would be helpful.

I think not. Can we instead link to some other documentation?
