### ISSUE TITLE
proposal: more provider clients

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_kv_oauth#42]
- [ ] Amazon
- [ ] Azure
- [x] Discord
- [x] Facebook
- [x] GitHub
- [x] GitLab
- [x] Google
- [x] Slack
- [x] Twitter

**Comment by lino-levan** [comment]
What's the vision on this?

**Comment by iuioiua** [comment]
I'll do Twitter.

**Comment by iuioiua** [comment]
Removing Twitch as it doesn't support PKCE.

**Comment by iuioiua** [comment]
I've removed LinkedIn. I don't think it's that sought-after.

**Comment by iuioiua** [comment]
I'll close this now. We now have a sufficient number of providers we provide OAuth 2.0 configurations for. I'll create a new issue that takes care of continuing to cater for more providers. Thank you for all your efforts, @lino-levan and @j3lte!
