### ISSUE TITLE
todo: `demo_test.ts`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_kv_oauth#61]
It should:
* Import `handler()` from `demo.ts` and use `serve()` from `std`.
* Use the `signal` property to close the server once tests are completed.
* Basically, ensure the demo server starts fine and endpoints are responsive, but provide 100% test coverage, if possible. In-depth testing of `deno_kv_oauth`'s functions is not needed, as that's taken care

**Comment by lino-levan** [comment]
Makes sense to me.
