### ISSUE TITLE
proposal: able to customize `redirectUrl` in `callback`

### ISSUE THREAD

**Issue by huai-jie** [denoland/deno_kv_oauth#70]
For use case like https://github.com/denoland/saaskit/pull/249

**Comment by lino-levan** [comment]
`callback` accepts an optional `redirectUrl` parameter. Maybe I'm not understanding the request though?

<img width="301" alt="image" src="https://github.com/denoland/deno_kv_oauth/assets/11367844/177f4a07-0025-42d5-81fc-8207d05afdd4">

**Comment by iuioiua** [comment]
> `callback` accepts an optional `redirectUrl` parameter. Maybe I'm not understanding the request though?
> 
> 
> 
> <img width="301" alt="image" src="https://github.com/denoland/deno_kv_oauth/assets/11367844/177f4a07-0025-42d5-81fc-8207d05afdd4">
> 
> 

Correct. Are you aware of this, @kit?

**Comment by iuioiua** [comment]
I believe that the feature you asked for is already implemented. Please feel free to re-open this if I'm wrong.

**Comment by huai-jie** [comment]
Oh 😲. I do not aware about this. 

Okay, would try to use it 👍

Nit: Maybe we could write a documentation for it?

**Comment by iuioiua** [comment]
Yeah, on the to-do list 🤣
